name: Java CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
    - 1.3.x
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-micronaut-core-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-gradle-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-micronaut-core-wrapper-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-wrapper-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: ./gradlew publishToMavenLocal --no-daemon --parallel --continue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: ./gradlew publish --no-daemon
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
